ce_permanence:
    resource: "@CEPermanenceBundle/Resources/config/routing.yml"
    prefix:   /

ce_reservation:
    resource: "@CEReservationBundle/Resources/config/routing.yml"
    prefix:   /

ce_device:
    resource: "@CEDeviceBundle/Resources/config/routing.yml"
    prefix:   /

ce_user:
    resource: "@CEUserBundle/Resources/config/routing.yml"
    prefix:   /

ce_core:
    resource: "@CECoreBundle/Resources/config/routing.yml"
    prefix:   /core

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

