<?php

namespace CE\DeviceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceRepository extends EntityRepository
{
    public function findByDisponible($disponible){
        $qb = $this->createQueryBuilder('d')
            ->where("d.disponible = :dispo")
            ->orderBy("d.libelle")
            ->setParameter('dispo', $disponible);

        return $qb;
    }
}
