<?php

namespace CE\DeviceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends EntityRepository
{
    public function findAllSortByLibelle()
    {
        return $this->createQueryBuilder('m')
            ->orderBy('m.libelle', 'ASC')
            ->getQuery()
            ->getResult();
    }
    
}
