<?php

namespace CE\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findActif()
    {
        $qb = $this->createQueryBuilder('u')
            ->where("u.enabled = 1")
            ->orderBy('u.name, u.firstname');
        return $qb;
    }
}
