<?php

namespace CE\PermanenceBundle\Entity;

/**
 * PermanenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermanenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBetween($startDate, $endDate)
    {
        return $this->createQueryBuilder('p')
            ->where('p.startDate BETWEEN :startDate and :endDate')
            ->setParameter('startDate', $startDate->format('Y-m-d H:i:s'))
            ->setParameter('endDate', $endDate->format('Y-m-d H:i:s'))
            ->getQuery()->getResult();
    }
}
