<?php

namespace CE\PermanenceBundle\Entity;

/**
 * PermanenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermanenceRepository extends \Doctrine\ORM\EntityRepository
{
}
