CREATE TABLE BannedPeriod (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, startDate DATETIME NOT NULL, endDate DATETIME NOT NULL, commentaire VARCHAR(255) DEFAULT NULL, INDEX IDX_F97CB47FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE user_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE INDEX UNIQ_8F02BF9D5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE User (id INT AUTO_INCREMENT NOT NULL, user_user_group INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, locked TINYINT(1) NOT NULL, expired TINYINT(1) NOT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', credentials_expired TINYINT(1) NOT NULL, credentials_expire_at DATETIME DEFAULT NULL, identifiant VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, phoneNumber VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_2DA1797792FC23A8 (username_canonical), UNIQUE INDEX UNIQ_2DA17977A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_2DA17977C05FB297 (confirmation_token), INDEX IDX_2DA1797728657971 (user_user_group), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Category (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, code VARCHAR(16) NOT NULL, libelle VARCHAR(32) NOT NULL, INDEX IDX_FF3A7B97727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Device (id INT AUTO_INCREMENT NOT NULL, marque_id INT DEFAULT NULL, image_id INT DEFAULT NULL, reference VARCHAR(50) NOT NULL, libelle VARCHAR(255) NOT NULL, modele VARCHAR(255) NOT NULL, disponible TINYINT(1) NOT NULL, disponibleLib VARCHAR(255) DEFAULT NULL, commentaire VARCHAR(1024) DEFAULT NULL, date_achat DATE NOT NULL, emplacement VARCHAR(32) DEFAULT NULL, INDEX IDX_E83B3B84827B9B2 (marque_id), UNIQUE INDEX UNIQ_E83B3B83DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE device_category (device_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_887840E194A4C7D4 (device_id), INDEX IDX_887840E112469DE2 (category_id), PRIMARY KEY(device_id, category_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE History (id INT AUTO_INCREMENT NOT NULL, device_id INT NOT NULL, date DATETIME NOT NULL, trace LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Image (id INT AUTO_INCREMENT NOT NULL, url VARCHAR(255) NOT NULL, alt VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Marque (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Reservation (id INT AUTO_INCREMENT NOT NULL, device_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status_id INT DEFAULT NULL, startDate DATETIME NOT NULL, endDate DATETIME NOT NULL, commentaire VARCHAR(1024) DEFAULT NULL, INDEX IDX_C454C68294A4C7D4 (device_id), INDEX IDX_C454C682A76ED395 (user_id), INDEX IDX_C454C6826BF700BD (status_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE ReservationStatus (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE Permanence (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, startDate DATETIME NOT NULL, endDate DATETIME NOT NULL, allDay TINYINT(1) NOT NULL, INDEX IDX_906DC866A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE BannedPeriod ADD CONSTRAINT FK_F97CB47FA76ED395 FOREIGN KEY (user_id) REFERENCES User (id);
ALTER TABLE User ADD CONSTRAINT FK_2DA1797728657971 FOREIGN KEY (user_user_group) REFERENCES user_group (id);
ALTER TABLE Category ADD CONSTRAINT FK_FF3A7B97727ACA70 FOREIGN KEY (parent_id) REFERENCES Category (id);
ALTER TABLE Device ADD CONSTRAINT FK_E83B3B84827B9B2 FOREIGN KEY (marque_id) REFERENCES Marque (id);
ALTER TABLE Device ADD CONSTRAINT FK_E83B3B83DA5256D FOREIGN KEY (image_id) REFERENCES Image (id);
ALTER TABLE device_category ADD CONSTRAINT FK_887840E194A4C7D4 FOREIGN KEY (device_id) REFERENCES Device (id) ON DELETE CASCADE;
ALTER TABLE device_category ADD CONSTRAINT FK_887840E112469DE2 FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE CASCADE;
ALTER TABLE Reservation ADD CONSTRAINT FK_C454C68294A4C7D4 FOREIGN KEY (device_id) REFERENCES Device (id);
ALTER TABLE Reservation ADD CONSTRAINT FK_C454C682A76ED395 FOREIGN KEY (user_id) REFERENCES User (id);
ALTER TABLE Reservation ADD CONSTRAINT FK_C454C6826BF700BD FOREIGN KEY (status_id) REFERENCES ReservationStatus (id);
ALTER TABLE Permanence ADD CONSTRAINT FK_906DC866A76ED395 FOREIGN KEY (user_id) REFERENCES User (id);


insert  into `ReservationStatus`(`id`,`libelle`) values (1,'Réservé'),(2,'Emprunté'),(3,'Restitué');

insert  into `user_group`(`id`,`name`,`roles`) values (1,'Administrateurs','a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}'),(2,'Membres de la section bricolage','a:1:{i:0;s:10:\"ROLE_ADMIN\";}'),(3,'Salariés','a:1:{i:0;s:16:\"ROLE_READ_DEVICE\";}');

insert  into `User`(`id`,`user_user_group`,`username`,`username_canonical`,`email`,`email_canonical`,`enabled`,`salt`,`password`,`last_login`,`locked`,`expired`,`expires_at`,`confirmation_token`,`password_requested_at`,`roles`,`credentials_expired`,`credentials_expire_at`,`identifiant`,`firstname`,`phoneNumber`) values (1,1,'admin','admin','ce.tsv.bricolage@gmail.com','ce.tsv.bricolage@gmail.com',1,'i5ux8lzmvogk0400c8o88wkwsg44w4c','0ovyRtBeClpQJre+Uv9hB+vi1log19Pvaop5hBTFCIaTFPUEcRSYomaxpT1pZ1dCw+tb/OFUt6OP3dupJYpUUw==','2016-04-28 10:38:49',0,0,NULL,NULL,NULL,'a:1:{i:0;s:16:\"ROLE_SUPER_ADMIN\";}',0,NULL,'Administrateur','Administrateur','0557298014');

