<?php

namespace CE\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function findByReservationStatus($id) {
        return $this->createQueryBuilder("r")->where('r.status = :id')->setParameter('id', $id)->getQuery()->getResult();
    }
}
