<?php

namespace CE\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
    public function findByReservationStatus($id) {
        return $this->createQueryBuilder("r")->where('r.status = :id')->setParameter('id', $id)->getQuery()->getResult();
    }



    public function findByDate($startDate,$endDate) {

        $result = $this->createQueryBuilder("r")
            ->where('r.endDate >= :startDate AND r.endDate <= :endDate')
            ->orWhere('r.startDate >= :startDate AND r.endDate <= :endDate')
            ->orWhere('r.startDate <= :endDate AND r.startDate >= :startDate')
            ->orWhere('r.startDate <= :startDate AND r.endDate >= :endDate')
            ->setParameter('startDate', $startDate)
            ->setParameter('endDate', $endDate)
            ->getQuery();

        return $result->getResult();
    }

}
